### ISSUE TITLE
`docker-compose.yml` 的使用者名稱被固定了

### ISSUE THREAD

**Issue by c1ydehhx** [stwater20/DOMjudge-docker-compose#1]
在 `docker-compose.yml` 中，`dj-mariadb` 的 service 中，`volume` 為 `/home/iming/backup:/var/lib/mysql`，使用者被固定成了 `iming`。

建議使用 `$USER` 來取得使用者名稱，也就是

```
dj-mariadb:
        image: mariadb
        volumes:
                #「:」前面的部分是備份資料庫的路徑，可以避免重新部署後資料消失
                - /home/$USER/backup:/var/lib/mysql
        environment:
                - MYSQL_ROOT_PASSWORD=rootpw
                - MYSQL_DATABASE=domjudge
                - MYSQL_USER=domjudge
                - MYSQL_PASSWORD=djpw
        ports:
                - 13306:3306
        command:
                --max-connections=1000
```
